env:
  browser: true
  es2020: true
extends:
  - 'plugin:react-hooks/recommended'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 11
  sourceType: module
plugins:
  - react-hooks
rules: {}
