version: "3.7"
services:
  web:
    build: .
    ports:
      - 8080:8080
    environment:
      - POSTGRES_DB=vtk
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_HIKARI_CONNECTION-TIMEOUT=10000
    depends_on:
      - db
    networks:
      - tesis
  db:
    image: postgres
    ports:
    - 2345:5432
    restart: always
    secrets:
      - db-password
    networks:
      - tesis
    environment:
      - POSTGRES_DB=vtk
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
secrets:
  db-password:
    file: docker/db/password.txt
networks:
  tesis:
