spring:
  application:
    name: "vtkDemo"

  datasource:
    url: jdbc:postgresql://localhost:5432/vtk?applicationName=${spring.application.name}
    username: "vtkapp_user"
    password: "vtk4ppus3r"

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

logging:
  level:
    org.springframework: INFO
    com.example.vtkdemo: DEBUG

management:
  endpoints:
    web:
      exposure:
        exclude: "*"

application:
  tempFolder: @project.basedir@/tmp
  rest-template-login: false


servers:
  orthanc:
    host: localhost
    port: 8042
    endpoints:
      find: "/tools/find/"
      instances: "/instances/{instance}/file"