spring:
  application:
    name: "vtkDemo"

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/vtk}?applicationName=${spring.application.name}
    username: ${SPRING_DATASOURCE_USERNAME:vtkapp_user}
    password: ${SPRING_DATASOURCE_PASSWORD:vtk4ppus3r}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    open-in-view: false

logging:
  level:
    root: INFO
    org.springframework: INFO
    com.example.vtkdemo: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"

application:
  tempFolder: ${BUILD_DIR:.}/tmp
  rest-template-login: false


servers:
  orthanc:
    host: localhost
    port: 8042
    endpoints:
      find: "/tools/find/"
      instances: "/instances/{instance}/file"