spring:
  application:
    name: "vtkDemo"

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/vtk}?applicationName=${spring.application.name}
    username: ${SPRING_DATASOURCE_USERNAME:vtkapp_user}
    password: ${SPRING_DATASOURCE_PASSWORD:vtk4ppus3r}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    open-in-view: false

  data:
    rest:
      base-path: /api

  thymeleaf:
    cache: false

logging:
  level:
    root: INFO
    org.springframework: INFO
    com.example.vtkdemo: DEBUG
    org.atmosphere: WARN

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
    shutdown:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
        step: 5s

endpoints:
  shutdown:
    enabled: true

application:
  tempFolder: ${BUILD_DIR:.}/tmp
  rest-template-login: false


servers:
  orthanc:
    host: localhost
    port: 8042
    scheme: http
    endpoints:
      find: "/tools/find/"
      instances: "/instances/{instance}/file"
    auth-Enabled: true
    username: orthanc
    password: 0rth4ncP4ssw0rd

server:
  port: 8080
  shutdown: graceful
